Fixed computed ptr with group by incorrectly inferring multiplicity. (#8485)
Fixes query errors caused by using group by in a computed pointer.

For example, given the schema:
```
module default {
    type Foo { n: int64 };
    type Bar { multi foo: Foo };
}
```

The query `SELECT Bar { g := (group .foo by .n) };` would produce the error:
```
QueryError: possibly not a distinct set returned by an expression for a computed link 'g'
  ┌─ <query>:1:14
  │
1 │ SELECT Bar { g := (group .foo by .n) };
  │              ^^^^^^^^^^^^^^^^^^^^^^ You can use assert_distinct() around the expression to turn this into a runtime assertion, or the DISTINCT operator to silently discard duplicate elements.
```